### ISSUE TITLE
NFS 'nolock' problems on mount

### ISSUE THREAD

**Issue by andybrucenet** [streamplace/kube-for-mac#1]
Thanks for this project - I love using k8s natively on the docker alpine image (no need for virtualbox - yeah!)

But - I've spent quite a few hours debugging a mysterious problem.

Turns out that I cannot get 'mount -t nfs' working without specifying 'nolock'. The call simply hangs - and eventually k8s gets tired of waiting and says "timed out".

At the native docker alpine vm layer (e.g. `screen ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty`) I get exactly the same lockup. Running through strace gives me...zilch.

It's too bad that NFS options are only deemed necessary starting with v1.6 k8s.

I have a workaround:
<pre>
apk update && apk add nfs-utils tcpdump findmnt file
cp /bin/mount /
</pre>

I modified your start script not to copy 'mount' if it already exists.

So the above gives us mount.nfs (which is not on the Docker xhyve alpine image) but it still stalls during a mount. So I hacked away and used this as a replacement for /mount in your start script:
<pre>
if ! onVM which mount.nfs; then
  bigLog "Adding necessary dependency mount.nfs..."
  onVM apk update
  onVM apk add nfs-utils
fi

# I have no idea why this is, but once kubelet starts running it expects mount to be at /mount.
bigLog "Copying mount for poorly-understood reasons..."
if ! onVM ls /mount 2>/dev/null ; then
  #onVM cp /bin/mount /mount
  nsenter --mount=/rootfs/proc/1/ns/mnt -- ash -c "echo '#!/bin/sh' > /mount"
  nsenter --mount=/rootfs/proc/1/ns/mnt -- ash -c "echo 'if /bin/echo \"\$*\" | /bin/grep -q -e \"-t nfs\" ; then' >> /mount"
  nsenter --mount=/rootfs/proc/1/ns/mnt -- ash -c "echo '  the_good_value=\$(/bin/echo \"\$*\" | /bin/sed -e \"s/^\(.*\)-t nfs\(.*\)/\1-t nfs -o nolock \2/\")' >> /mount"
  nsenter --mount=/rootfs/proc/1/ns/mnt -- ash -c "echo '  eval /bin/mount \$the_good_value' >> /mount"
  nsenter --mount=/rootfs/proc/1/ns/mnt -- ash -c "echo 'else' >> /mount"
  nsenter --mount=/rootfs/proc/1/ns/mnt -- ash -c "echo '  eval /bin/mount \$*' >> /mount"
  nsenter --mount=/rootfs/proc/1/ns/mnt -- ash -c "echo 'fi' >> /mount"
  onVM chmod +x /mount
fi
</pre>

I can fork and push my changes if you want 'em, but I'm curious if you are planning on giving us a handy 1.6 kubernetes? Of course 1.6 has lots of changes which I must learn, but if you are already on this task??

I think moving up to 1.6 will fix the problem via support for:
<pre>
annotations:
    volume.beta.kubernetes.io/mount-options: "nolock"
</pre>

But until then, direct calls to vanilla 'mount' on the docker alpine image block. Although I promise you I have all v3 and v4 NFS ports open on the analogous NFS servers...

**Comment by iameli** [comment]
Fascinating! I'd love to see a pull request with your changes.

I haven't used `kube-for-mac` in a few weeks but I just started up a contract to build a Kubernetes devleopment environment so I'm going to be diving into it very soon -- at that point I'll try and get it working with Kube 1.6.

Do you have any idea what's up with the fact that Kubernetes seems to expect the `mount` binary at `/mount`, rather than something reasonable like `/sbin/mount`? That's just about the weirdest hack I've ever had to include in my code.

**Comment by andybrucenet** [comment]
Hmm - I already pushed this so I'm taking the opportunity to close the ticket. Hope that's OK...
